pipeline {
    agent any
    
    parameters {
        string(name: 'BRANCH', defaultValue: 'main', description: 'Branch to build')
    }

    stages {
        stage('Greet') {
            steps {
                echo "Hello ${params.BRANCH}"
            }
        }
    }
}
